### ISSUE TITLE
Sorted robots.txt

### ISSUE THREAD

**Issue by LeMoussel** [bopoda/robots-txt-parser#13]
From Google Robots.txt Specifications - [Google-supported non-group-member records](https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt?hl=en#google-supported-non-group-member-records)

> At a group-member level, in particular for allow and disallow directives, the most specific rule based on the length of the [path] entry will trump the less specific (shorter) rule. The order of precedence for rules with wildcards is undefined.

**Source robots.txt:**
```
User-agent: *
Allow: /p
Disallow: /
Allow: /folder/
Disallow: /folder
Allow: /page
Disallow: /*.htm
Allow: /$
```

**Sorted robots.txt:** `$this->getOrderedDirectivesByUserAgent($userAgent)`
```
array(7) {
  [0] =>
  array(3) {
    'directive' =>
    string(8) "disallow"
    'rule' =>
    string(1) "/"
    'rule_regexp' =>
    string(6) "/^\//i"
  }
  [1] =>
  array(3) {
    'directive' =>
    string(5) "allow"
    'rule' =>
    string(2) "/p"
    'rule_regexp' =>
    string(7) "/^\/p/i"
  }
  [2] =>
  array(3) {
    'directive' =>
    string(5) "allow"
    'rule' =>
    string(2) "/$"
    'rule_regexp' =>
    string(7) "/^\/$/i"
  }
  [3] =>
  array(3) {
    'directive' =>
    string(5) "allow"
    'rule' =>
    string(5) "/page"
    'rule_regexp' =>
    string(10) "/^\/page/i"
  }
  [4] =>  
   array(3) {
    'directive' =>
    string(8) "disallow"
    'rule' =>
    string(6) "/*.htm"
    'rule_regexp' =>
    string(13) "/^\/.*\.htm/i"
  }
  [5] =>
  array(3) {
    'directive' =>
    string(8) "disallow"
    'rule' =>
    string(7) "/folder"
    'rule_regexp' =>
    string(12) "/^\/folder/i"
  }
  [6] =>
  array(3) {
    'directive' =>
    string(5) "allow"
    'rule' =>
    string(8) "/folder/"
    'rule_regexp' =>
    string(14) "/^\/folder\//i"
  }
}
```
**Result:**
> Disallow: /
> Allow: /p
> Allow: /$
> Allow: /page
> Disallow: /*.htm
> Disallow: /folder
> Allow: /folder/

**Expected result:**
> Allow: /folder/
> Disallow: /folder
> Allow: /page
> Allow: /p (Rem: for the same length, Allow directive first)
> Allow: /$ (Rem: for the same length, Allow directive first)
> Disallow: /*.htm (Rem: lenghth = 2 because stop at the wildcard)
> Disallow: /

**Comment by bopoda** [comment]
Hi @LeMoussel 
i can`t agree with you. Need to check specific cases.

First example, according to google robots.txt tester:
```
User-agent: *
Allow: /anyfolder   #length 10 exactly
Disallow: /*.html    #length 2 or 7?
```

url "`/anyfolder.html`" will be **disallowed**. It means the longest value is more significant. RobotsTxtValidator is correct in this case. (Google - The order of precedence for rules with wildcards is undefined.)

Second example using google robots.txt tester:
```
User-agent: *
Allow: /any   #length 4 exactly
Disallow: /*.html    #length 2 or 7?
```
url "`/anyfolder.html`" will be **allowed**. So, it means allow directive is more significant, so disallow length is 7 (not 2). RobotsTxtValidator is correct here.

Third example using google robots.txt tester:
```
User-agent: *
Allow: /any   #length 4 
Disallow: /any*    #length 5
```
url "`/any`" will be **allowed**. So, it means here length has been calculated as 5 for disallow directive. RobotsTxtValidator is correct here again.

Do you have similar examples which is not correct according to Google robots.txt tester?

**Comment by LeMoussel** [comment]
You are right.

Good results are obtained as described in Sample situations of [Google Robots.txt Specifications - Google-supported non-group-member records](https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt?hl=en#order-of-precedence-for-group-member-records).
