### ISSUE TITLE
Some robots.txt files for robustness testing

### ISSUE THREAD

**Issue by LeMoussel** [bopoda/robots-txt-parser#17]
For robustness testing, 

**Confused robots.txt files:** 
[http://www.cooljobscanada.com/robots.txt](http://www.cooljobscanada.com/robots.txt)
[http://www.crowndiamond.org/robots.txt](http://www.crowndiamond.org/robots.txt)
[http://ramast.divagaciones.com/robots.txt](http://ramast.divagaciones.com/robots.txt)

**Big robots.txt file:** 
[http://www.goldmansachs.com/robots.txt](http://www.goldmansachs.com/robots.txt)

**Comment by bopoda** [comment]
**Confused robots.txt files:**
http://robots.jeka.by/cooljobscanada.com (parsed)
http://robots.jeka.by/crowndiamond.org (parsed with empty rules - seems as bug which depends with encoding)
http://robots.jeka.by/ramast.divagaciones.com (parsed with empty rules but it is correctly)

**Big robots.txt file:**
http://robots.jeka.by/goldmansachs.com (parsed during less than 0.5 sec now)

Additional issue created https://github.com/bopoda/robots-txt-parser/issues/40 for crowndiamond.org.
