### ISSUE TITLE
Directive with '+' not handled correctly

### ISSUE THREAD

**Issue by LeMoussel** [bopoda/robots-txt-parser#48]
Bad detection if presence of `+` in the directive.

```
$robotsTxtContentIssue = "
User-agent: *
Disallow: *telecommande++*
";

$parserRobotsTxt = RobotsDotText::withContent($robotsTxtContentIssue);
$rulesRobotsTxt = $parserRobotsTxt->getRules();
$robotsTxtValidator = new RobotsTxtValidator($rulesRobotsTxt);

if ($robotsTxtValidator->isUrlAllow('http://www.test.com/telecommandes-box-decodeur.html')) {
        echo "Allow.".PHP_EOL;
} else {
        echo "Disallow.".PHP_EOL;
}
```
**Result :**
> Disallow

**Should be :**
> Allow

**Google search console - robots.txt Tester :**
![image](https://cloud.githubusercontent.com/assets/1816573/24792192/421cb5b0-1b7d-11e7-8609-3e46ad43b864.png)

Per Google’s robots.txt documentation, the `+` has no special meaning, but * has one (it means: any sequence of characters).
So crawling of `/telecommandes-box-decodeur.html` would still be allowed.
Disallowed would be, for example, crawling of `/foo/telecommande++bar.html`.

Maybe one solution would be to add `\` from some special regular expression characters except `*` (`*telecommande++*` => `*telecommande\+\+*`)

**Comment by bopoda** [comment]
Hi @LeMoussel,
should be fixed by this [line](https://github.com/bopoda/robots-txt-parser/commit/cef35b5a535448d156559564b1a0830d1882cd60#diff-db779d60a11b28e63a7ed996374d8ca5R195). 
Please write if something else.
