### ISSUE TITLE
Suppress space in User_Agent

### ISSUE THREAD

**Issue by LeMoussel** [bopoda/robots-txt-parser#5]
If user-agent has a spacing in its name,  robots-txt-parser remove spaces. Is it normal ?

> User-agent:Googlebot
> Disallow:/
> User-agent:Cocon.Se Crawler
> Disallow:/

Got 'cocon.secrawler' in array result of `getRules()`
>     [cocon.secrawler] => Array
>         (
>             [disallow] => Array
>                 (
>                     [0] => /
>                 )
>         )

**Comment by bopoda** [comment]
@LeMoussel hey,
Thanks for feedback! Agree.

Now will return user-agent in lower case without removed whitespaces.
