### ISSUE TITLE
Could you publish this package to packagist ?

### ISSUE THREAD

**Issue by lyrixx** [bopoda/robots-txt-parser#53]
Hello,

Could you add a [composer.json ](https://getcomposer.org/) and then publish this package to [packagist](https://packagist.org/) ? 

Thanks

**Comment by lyrixx** [comment]
ping @bopoda

**Comment by bopoda** [comment]
Hi @lyrixx,

Could you please have a look at [PR](https://github.com/bopoda/robots-txt-parser/pull/55) before I merge? Do you have any suggestions regarding it?

**Comment by bopoda** [comment]
[bopoda/robots-txt-parser](https://packagist.org/packages/bopoda/robots-txt-parser) is available on [packagist](https://packagist.org/) now. 
@lyrixx, thank you very much! Please write if something else.

**Comment by lyrixx** [comment]
Thanks a lot.
It seems releases a missing on packagist. Maybe it's because the tag does not follow the pattern vX.Y.Z. Could you try to release v2.3.0?
(or maybe it does not work because there was no `composer.json` in the previous releases)

**Comment by bopoda** [comment]
Thanks for the feedback.
I've created tag v2.3.0. Does it fix the issue? I see dev-master and v2.3.0 on packagist
